### ISSUE TITLE
I am getting an UnidentifiedImageError, when I try to train my model

### ISSUE THREAD

**Issue by anis-agwan** [Suji04/Chat_ScreenShot_Classifier#6]
UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x63a807fb0>
'''
classifier.fit_generator(training_set,
                         steps_per_epoch = 8000,
                         epochs = 25,
                         validation_data = test_set,
                         validation_steps = 2000)
'''

**Comment by anis-agwan** [comment]
![Screenshot 2020-06-07 at 9 33 20 PM](https://user-images.githubusercontent.com/59297399/83973830-93a23300-a906-11ea-9b05-cf0ad86c6da5.png)

**Comment by Suji04** [comment]
@anis-agwan What is the output of flow_from_directory function just before the training?
If it's correctly showing the number of images in every class then check for possible corrupted images.

**Comment by anis-agwan** [comment]
My output showing the same as yours, the same as it should be for flow_from_directory. I also checked the files and there are no corrupt images, these errors occur at random

**Comment by Suji04** [comment]
You can try updating your Pillow and Keras library. After that, you should create an issue in the Keras repo.
